name: multimodal_ml
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anyio=4.10.0=py311haa95532_0
  - argon2-cffi=25.1.0=py311haa95532_0
  - argon2-cffi-bindings=25.1.0=py311h02ab6af_0
  - asttokens=3.0.0=py311haa95532_0
  - async-lru=2.0.5=py311haa95532_0
  - attrs=25.4.0=py311haa95532_2
  - babel=2.17.0=py311haa95532_0
  - blas=1.0=mkl
  - bleach=6.3.0=py311haa95532_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotlicffi=1.2.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2026.01.04=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.3=py311haa95532_0
  - contourpy=1.3.3=py311h3fd045d_3
  - cpuonly=2.0=0
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.16=py311h885b0b7_1
  - decorator=5.2.1=py311haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - double-conversion=3.3.1=he0c23c2_0
  - executing=2.2.1=py311haa95532_0
  - expat=2.7.3=h885b0b7_4
  - filelock=3.20.3=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311h3f79411_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - h11=0.16.0=py311haa95532_1
  - harfbuzz=11.0.0=h9e37d49_0
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py311haa95532_0
  - httpx=0.28.1=py311haa95532_1
  - icu=75.1=he0c23c2_0
  - idna=3.11=py311haa95532_0
  - intel-openmp=2025.3.0=h57928b3_642
  - ipykernel=6.31.0=py311h4442805_0
  - ipython=9.7.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - ipywidgets=8.1.7=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.12.1=py311haa95532_0
  - jsonschema-specifications=2025.9.1=py311haa95532_0
  - jupyter=1.1.1=py311haa95532_0
  - jupyter-lsp=2.2.5=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_1
  - jupyter_console=6.6.3=py311haa95532_0
  - jupyter_core=5.9.1=py311haa95532_0
  - jupyter_events=0.12.0=py311haa95532_1
  - jupyter_server=2.17.0=py311haa95532_0
  - jupyter_server_terminals=0.5.3=py311haa95532_0
  - jupyterlab=4.5.0=py311haa95532_0
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - jupyterlab_server=2.28.0=py311haa95532_0
  - jupyterlab_widgets=3.0.15=py311haa95532_0
  - kiwisolver=1.4.9=py311h275cad7_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.9.0=13_hc41557d_netlib
  - libclang13=21.1.8=default_ha2db4b5_1
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.84.0=h7025463_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=13_h018ca30_netlib
  - libpng=1.6.54=h7351971_0
  - libsodium=1.0.20=h83e8143_0
  - libsqlite=3.51.2=hf5d6505_0
  - libtiff=4.7.0=hfc51747_1
  - libuv=1.51.0=hfd05255_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h02ab6af_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib=3.10.8=py311h1ea47a8_0
  - matplotlib-base=3.10.8=py311h1675fdf_0
  - matplotlib-inline=0.2.1=py311haa95532_0
  - mistune=3.1.2=py311haa95532_0
  - mkl=2023.1.0=h6a75c08_48682
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.2=py311haa95532_0
  - nbconvert=7.16.6=py311haa95532_0
  - nbconvert-core=7.16.6=py311haa95532_0
  - nbconvert-pandoc=7.16.6=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - networkx=3.6.1=pyhcf101f3_0
  - notebook=7.5.0=py311haa95532_0
  - notebook-shim=0.2.4=py311haa95532_0
  - numpy=1.26.4=py311h0b4df5a_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.0=h725018a_0
  - overrides=7.7.0=py311haa95532_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.1.4=py311hf63dbb6_0
  - pandoc=3.8=haa95532_0
  - pandocfilters=1.5.1=py311haa95532_0
  - parso=0.8.5=py311haa95532_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.44=h99c9b8b_2
  - pillow=10.4.0=py311h5592be9_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - prometheus_client=0.21.1=py311haa95532_0
  - prompt-toolkit=3.0.52=py311haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311h02ab6af_1
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.3=py311haa95532_0
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=py311haa95532_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyside6=6.9.0=py311h9f82be6_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=py311haa95532_0
  - python-json-logger=4.0.0=py311haa95532_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytorch=2.5.1=py3.11_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py311h885b0b7_0
  - pywinpty=2.0.15=py311h72d21ff_0
  - pyyaml=6.0.3=py311h3f79411_0
  - pyzmq=27.1.0=py311h7149c55_1
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.0=h83cda92_0
  - qtconsole=5.7.0=py311haa95532_0
  - qtpy=2.4.3=py311haa95532_0
  - referencing=0.37.0=py311haa95532_0
  - requests=2.32.5=py311haa95532_1
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - scikit-learn=1.8.0=np2py311hd01f973_1
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=py311haa95532_0
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=py311haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=py311haa95532_0
  - statsmodels=0.14.6=py311h17033d2_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=hd094cb3_4
  - terminado=0.18.1=py311haa95532_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py311h3485c13_0
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.0=py311h3485c13_1
  - urllib3=2.6.3=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=py311haa95532_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=1.8.0=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - widgetsnbextension=4.0.14=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - winpty=0.4.3=4
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - altair==6.0.0
      - beautifulsoup4==4.14.3
      - blinker==1.9.0
      - cachetools==6.2.4
      - click==8.3.1
      - curl-cffi==0.13.0
      - frozendict==2.4.7
      - gitdb==4.0.12
      - gitpython==3.1.46
      - jsonschema==4.26.0
      - multitasking==0.0.12
      - narwhals==2.15.0
      - peewee==3.19.0
      - platformdirs==4.5.1
      - protobuf==6.33.4
      - pyarrow==22.0.0
      - pydeck==0.9.1
      - python-dotenv==1.2.1
      - rpds-py==0.30.0
      - scipy==1.17.0
      - smmap==5.0.2
      - soupsieve==2.8.1
      - streamlit==1.52.2
      - tenacity==9.1.2
      - toml==0.10.2
      - watchdog==6.0.0
      - websockets==16.0
      - yfinance==1.0
prefix: D:\Anaconda\envs\multimodal_ml
